/**
 * Generated Convex API
 *
 * These exports are auto-generated by `npx convex dev`.
 * This file is a placeholder until Convex is configured.
 */

import { makeFunctionReference } from "convex/server";

// Helper to create function references for the api namespace
const fn = (name) => makeFunctionReference(name);

export const api = {
  "functions/clients": {
    getAll: fn("functions/clients:getAll"),
    getAllIncludingInactive: fn("functions/clients:getAllIncludingInactive"),
    getById: fn("functions/clients:getById"),
    getByLinearTeamKey: fn("functions/clients:getByLinearTeamKey"),
    create: fn("functions/clients:create"),
    update: fn("functions/clients:update"),
    deactivate: fn("functions/clients:deactivate"),
  },
  "functions/contingents": {
    getByClient: fn("functions/contingents:getByClient"),
    getAllByClient: fn("functions/contingents:getAllByClient"),
    getById: fn("functions/contingents:getById"),
    getUtilization: fn("functions/contingents:getUtilization"),
    create: fn("functions/contingents:create"),
    update: fn("functions/contingents:update"),
    addUsedHours: fn("functions/contingents:addUsedHours"),
    syncFromProductive: fn("functions/contingents:syncFromProductive"),
  },
  "functions/decisions": {
    getByTicket: fn("functions/decisions:getByTicket"),
    getById: fn("functions/decisions:getById"),
    getLatestByTicket: fn("functions/decisions:getLatestByTicket"),
    getHistoryByTicket: fn("functions/decisions:getHistoryByTicket"),
    create: fn("functions/decisions:create"),
    updateReasoning: fn("functions/decisions:updateReasoning"),
  },
  "functions/meetings": {
    getByClient: fn("functions/meetings:getByClient"),
    getById: fn("functions/meetings:getById"),
    getActiveMeeting: fn("functions/meetings:getActiveMeeting"),
    getWithDetails: fn("functions/meetings:getWithDetails"),
    getRecentByClient: fn("functions/meetings:getRecentByClient"),
    start: fn("functions/meetings:start"),
    addDecision: fn("functions/meetings:addDecision"),
    addAgendaTicket: fn("functions/meetings:addAgendaTicket"),
    end: fn("functions/meetings:end"),
    cancel: fn("functions/meetings:cancel"),
  },
  "functions/strategicGoals": {
    getByClient: fn("functions/strategicGoals:getByClient"),
    getActiveByClient: fn("functions/strategicGoals:getActiveByClient"),
    getById: fn("functions/strategicGoals:getById"),
    create: fn("functions/strategicGoals:create"),
    update: fn("functions/strategicGoals:update"),
    remove: fn("functions/strategicGoals:remove"),
    reorder: fn("functions/strategicGoals:reorder"),
  },
  "functions/tickets": {
    getByClient: fn("functions/tickets:getByClient"),
    getByStatus: fn("functions/tickets:getByStatus"),
    getById: fn("functions/tickets:getById"),
    getByLinearId: fn("functions/tickets:getByLinearId"),
    getDashboardStats: fn("functions/tickets:getDashboardStats"),
    getByStrategicGoal: fn("functions/tickets:getByStrategicGoal"),
    getActiveTickets: fn("functions/tickets:getActiveTickets"),
    upsertFromLinear: fn("functions/tickets:upsertFromLinear"),
    updateExploration: fn("functions/tickets:updateExploration"),
    linkToStrategicGoal: fn("functions/tickets:linkToStrategicGoal"),
  },
};

export const internal = {};
