/**
 * Generated Convex API types
 *
 * These types are auto-generated by `npx convex dev`.
 * This file is a placeholder until Convex is configured.
 */

import type { FunctionReference } from "convex/server";
import type { Id } from "./dataModel";

// Client types
type ClientDoc = {
  _id: Id<"clients">;
  isActive: boolean;
  linearTeamKey: string;
  name: string;
  productiveId?: string;
};

// Contingent types
type ContingentDoc = {
  _id: Id<"contingents">;
  clientId: Id<"clients">;
  lastUpdatedAt: string;
  period?: string;
  source: "manual" | "productive";
  totalHours: number;
  usedHours: number;
};

// Strategic Goal types
type StrategicGoalDoc = {
  _id: Id<"strategicGoals">;
  clientId: Id<"clients">;
  description: string;
  isActive: boolean;
  name: string;
  order: number;
};

// Ticket types
type TicketStatus = "backlog" | "exploration" | "decision" | "delivery" | "review" | "done" | "dropped";
type WorkType = "standard" | "maintenance";
type RiskLevel = "low" | "medium" | "high";

type TicketDoc = {
  _id: Id<"tickets">;
  clientId: Id<"clients">;
  explorationFindings?: string;
  explorationRound?: number;
  identifier: string;
  linearId: string;
  linearUpdatedAt: string;
  riskLevel?: RiskLevel;
  status: TicketStatus;
  strategicGoalId?: Id<"strategicGoals">;
  title: string;
  userStory?: string;
  workType: WorkType;
};

// Decision types
type DecisionOutcome = "go" | "iterate" | "no-go";

type DecisionDoc = {
  _id: Id<"decisions">;
  createdByEmail: string;
  explorationRound: number;
  outcome: DecisionOutcome;
  reasoning: string;
  ticketId: Id<"tickets">;
};

// Meeting types
type MeetingDoc = {
  _id: Id<"meetings">;
  agendaTicketIds: Id<"tickets">[];
  clientId: Id<"clients">;
  createdByEmail: string;
  decisionIds: Id<"decisions">[];
  endedAt?: string;
  startedAt: string;
};

// Dashboard Stats
type DashboardStats = {
  byRiskLevel: { high: number; low: number; medium: number; unassessed: number };
  byStatus: Record<TicketStatus, number>;
  byWorkType: Record<WorkType, number>;
  total: number;
};

// Meeting with details
type MeetingWithDetails = {
  meeting: MeetingDoc;
  agendaTickets: TicketDoc[];
  decisions: DecisionDoc[];
};

// API namespace types
export declare const api: {
  "functions/clients": {
    getAll: FunctionReference<"query", "public", Record<string, never>, ClientDoc[]>;
    getAllIncludingInactive: FunctionReference<"query", "public", Record<string, never>, ClientDoc[]>;
    getById: FunctionReference<"query", "public", { id: Id<"clients"> }, ClientDoc | null>;
    getByLinearTeamKey: FunctionReference<"query", "public", { linearTeamKey: string }, ClientDoc | null>;
    create: FunctionReference<"mutation", "public", { linearTeamKey: string; name: string; productiveId?: string }, Id<"clients">>;
    update: FunctionReference<"mutation", "public", { id: Id<"clients">; isActive?: boolean; linearTeamKey?: string; name?: string; productiveId?: string }, ClientDoc | null>;
    deactivate: FunctionReference<"mutation", "public", { id: Id<"clients"> }, ClientDoc | null>;
  };
  "functions/contingents": {
    getByClient: FunctionReference<"query", "public", { clientId: Id<"clients"> }, ContingentDoc | null>;
    getAllByClient: FunctionReference<"query", "public", { clientId: Id<"clients"> }, ContingentDoc[]>;
    getById: FunctionReference<"query", "public", { id: Id<"contingents"> }, ContingentDoc | null>;
    getUtilization: FunctionReference<"query", "public", { clientId: Id<"clients"> }, { contingent: ContingentDoc; remainingHours: number; utilizationPercent: number } | null>;
    create: FunctionReference<"mutation", "public", { clientId: Id<"clients">; period?: string; totalHours: number; usedHours?: number }, Id<"contingents">>;
    update: FunctionReference<"mutation", "public", { id: Id<"contingents">; period?: string; totalHours?: number; usedHours?: number }, ContingentDoc | null>;
    addUsedHours: FunctionReference<"mutation", "public", { id: Id<"contingents">; hours: number }, ContingentDoc | null>;
    syncFromProductive: FunctionReference<"mutation", "public", { clientId: Id<"clients">; period?: string; totalHours: number; usedHours: number }, Id<"contingents">>;
  };
  "functions/decisions": {
    getByTicket: FunctionReference<"query", "public", { ticketId: Id<"tickets"> }, DecisionDoc[]>;
    getById: FunctionReference<"query", "public", { id: Id<"decisions"> }, DecisionDoc | null>;
    getLatestByTicket: FunctionReference<"query", "public", { ticketId: Id<"tickets"> }, DecisionDoc | null>;
    getHistoryByTicket: FunctionReference<"query", "public", { ticketId: Id<"tickets"> }, { ticket: TicketDoc; decisions: DecisionDoc[] }>;
    create: FunctionReference<"mutation", "public", { ticketId: Id<"tickets">; outcome: DecisionOutcome; reasoning: string; explorationRound: number; createdByEmail: string }, Id<"decisions">>;
    updateReasoning: FunctionReference<"mutation", "public", { id: Id<"decisions">; reasoning: string }, DecisionDoc | null>;
  };
  "functions/meetings": {
    getByClient: FunctionReference<"query", "public", { clientId: Id<"clients"> }, MeetingDoc[]>;
    getById: FunctionReference<"query", "public", { id: Id<"meetings"> }, MeetingDoc | null>;
    getActiveMeeting: FunctionReference<"query", "public", { clientId: Id<"clients"> }, MeetingDoc | null>;
    getWithDetails: FunctionReference<"query", "public", { id: Id<"meetings"> }, MeetingWithDetails>;
    getRecentByClient: FunctionReference<"query", "public", { clientId: Id<"clients">; limit?: number }, MeetingDoc[]>;
    start: FunctionReference<"mutation", "public", { clientId: Id<"clients">; agendaTicketIds: Id<"tickets">[]; createdByEmail: string }, Id<"meetings">>;
    addDecision: FunctionReference<"mutation", "public", { meetingId: Id<"meetings">; decisionId: Id<"decisions"> }, MeetingDoc | null>;
    addAgendaTicket: FunctionReference<"mutation", "public", { meetingId: Id<"meetings">; ticketId: Id<"tickets"> }, MeetingDoc | null>;
    end: FunctionReference<"mutation", "public", { id: Id<"meetings"> }, MeetingDoc | null>;
    cancel: FunctionReference<"mutation", "public", { id: Id<"meetings"> }, void>;
  };
  "functions/strategicGoals": {
    getByClient: FunctionReference<"query", "public", { clientId: Id<"clients"> }, StrategicGoalDoc[]>;
    getActiveByClient: FunctionReference<"query", "public", { clientId: Id<"clients"> }, StrategicGoalDoc[]>;
    getById: FunctionReference<"query", "public", { id: Id<"strategicGoals"> }, StrategicGoalDoc | null>;
    create: FunctionReference<"mutation", "public", { clientId: Id<"clients">; name: string; description: string; order?: number }, Id<"strategicGoals">>;
    update: FunctionReference<"mutation", "public", { id: Id<"strategicGoals">; name?: string; description?: string; isActive?: boolean; order?: number }, StrategicGoalDoc | null>;
    remove: FunctionReference<"mutation", "public", { id: Id<"strategicGoals"> }, void>;
    reorder: FunctionReference<"mutation", "public", { clientId: Id<"clients">; goalIds: Id<"strategicGoals">[] }, void>;
  };
  "functions/tickets": {
    getByClient: FunctionReference<"query", "public", { clientId: Id<"clients"> }, TicketDoc[]>;
    getByStatus: FunctionReference<"query", "public", { clientId: Id<"clients">; status: TicketStatus }, TicketDoc[]>;
    getById: FunctionReference<"query", "public", { id: Id<"tickets"> }, TicketDoc | null>;
    getByLinearId: FunctionReference<"query", "public", { linearId: string }, TicketDoc | null>;
    getDashboardStats: FunctionReference<"query", "public", { clientId: Id<"clients"> }, DashboardStats>;
    getByStrategicGoal: FunctionReference<"query", "public", { strategicGoalId: Id<"strategicGoals"> }, TicketDoc[]>;
    getActiveTickets: FunctionReference<"query", "public", { clientId: Id<"clients"> }, TicketDoc[]>;
    upsertFromLinear: FunctionReference<"mutation", "public", { clientId: Id<"clients">; identifier: string; linearId: string; linearUpdatedAt: string; status: TicketStatus; title: string; workType: WorkType; explorationFindings?: string; explorationRound?: number; riskLevel?: RiskLevel; strategicGoalId?: Id<"strategicGoals">; userStory?: string }, Id<"tickets">>;
    updateExploration: FunctionReference<"mutation", "public", { id: Id<"tickets">; explorationFindings?: string; explorationRound?: number; riskLevel?: RiskLevel }, TicketDoc | null>;
    linkToStrategicGoal: FunctionReference<"mutation", "public", { ticketId: Id<"tickets">; strategicGoalId?: Id<"strategicGoals"> }, TicketDoc | null>;
  };
};

export declare const internal: Record<string, never>;
