/**
 * Generated Data Model types
 *
 * These types are auto-generated by `npx convex dev`.
 * This file is a placeholder until Convex is configured.
 */

import type { DataModelFromSchemaDefinition } from "convex/server";
import type { GenericId } from "convex/values";
import type schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;

export type Id<TableName extends TableNames> = GenericId<TableName>;

export type TableNames = keyof DataModel;

export type Doc<TableName extends TableNames> = DataModel[TableName]["document"];
