/**
 * Generated Server exports
 *
 * These exports are auto-generated by `npx convex dev`.
 * This file is a placeholder until Convex is configured.
 */

export {
  actionGeneric as action,
  actionGeneric as internalAction,
  httpActionGeneric as httpAction,
  mutationGeneric as mutation,
  mutationGeneric as internalMutation,
  queryGeneric as query,
  queryGeneric as internalQuery,
} from "convex/server";
